# Generated by Django 5.2.8 on 2025-11-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_rename_tables_for_clean_architecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationjob",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="evaluationjob",
            name="project_report",
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
        migrations.DeleteModel(
            name="EvaluationJob",
        ),
    ]
